final List<Product> products = [
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (1)'",
    shopavatar: "'assets/shop-image (1)'",
    title: "Bún bò nam bộ chùa láng",
    title2: "còn 2",
    price: "25.000",
    type: "đồ ăn nóng",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (2)'",
    shopavatar: "'assets/shop-image (2)'",
    title: "Bún bò nam bộ chùa láng",
    title2: "còn 2",
    price: "25.000",
    type: "đồ ăn nóng",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (3)'",
    shopavatar: "'assets/shop-image (3)'",
    title: "Bánh mì chả nóng Dũng",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (4)'",
    shopavatar: "'assets/shop-image (4)'",
    title: "Bánh Mì Tuhu Bread - Thụy Khuê",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (5)'",
    shopavatar: "'assets/shop-image (5)'",
    title: "Bành mì chả nóng Dũng",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (6)'",
    shopavatar: "'assets/shop-image (6)'",
    title: "Bành mì chả nóng Dũng",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (7)'",
    shopavatar: "'assets/shop-image (7)'",
    title: "Daebak - Thịt Nướng Hàn Quốc",
    title2: "còn 1",
    price: "25.000",
    type: "gói đồ ăn surprice",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (8)'",
    shopavatar: "'assets/shop-image (8)'",
    title: "Kem Trái Dừa & Thạch Dừa",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "11:00",
    shopcover: "'assets/shop-image (9)'",
    shopavatar: "'assets/shop-image (9)'",
    title: "Bành mì chả nóng Dũng",
    title2: "còn 2",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (10)'",
    shopavatar: "'assets/shop-image (10)'",
    title: "Cheap Corner -  Ship Đồ Ăn Đêm",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (10)'",
    shopavatar: "'assets/shop-image (10)'",
    title: "Dồi Sụn Nướng & Ăn Vặt",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (11)'",
    shopavatar: "'assets/shop-image (11)'",
    title: "Hồng Kỳ Quán -Lẩu Các Loại",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (12)'",
    shopavatar: "'assets/shop-image (12)'",
    title: "Hồng Kỳ Quán -Lẩu Các Loại",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (13)'",
    shopavatar: "'assets/shop-image (13)'",
    title: "Bún Ngan Hòe Nhai",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (14)'",
    shopavatar: "'assets/shop-image (14)'",
    title: "Bánh cuốn",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (15)'",
    shopavatar: "'assets/shop-image (15)'",
    title: "Tiger Sugar Fruit & Tea",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (16)'",
    shopavatar: "'assets/shop-image (16)'",
    title: "Tiệm Mỳ Indo Bảo Ngân",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (17)'",
    shopavatar: "'assets/shop-image (17)'",
    title: "Teen's Food",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (18)'",
    shopavatar: "'assets/shop-image (18)'",
    title: "Lẩu Gà Hầm Sâm Hàn Quốc",
    title2: "còn 1",
    price: "34.000",
    type: "đồ ăn nóng",
    distance: "1km",
    rate: "3.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "'assets/shop-image (19)'",
    shopavatar: "'assets/shop-image (19)'",
    title: "Bà Thìn - Xôi Chè & Bánh Trôi",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
];
