//list data product card
import 'list.dart';

List<Product> products = [
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (1).jpeg",
    shopavatar: "assets/image/shop-image (1).jpeg",
    title: "Bún bò nam bộ chùa láng",
    title2: "còn 2",
    price: "25.000",
    type: "đồ ăn nóng",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (2).jpg",
    shopavatar: "assets/image/shop-image (2).jpg",
    title: "Bún bò nam bộ chùa láng",
    title2: "còn 2",
    price: "25.000",
    type: "đồ ăn nóng",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (3).jpeg",
    shopavatar: "assets/image/shop-image (3).jpeg",
    title: "Bánh mì chả nóng Dũng",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (4).jpeg",
    shopavatar: "assets/image/shop-image (4).jpeg",
    title: "Bánh Mì Tuhu Bread - Thụy Khuê",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (5).jpg",
    shopavatar: "assets/image/shop-image (5).jpg",
    title: "Bành mì chả nóng Dũng",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (6).jpg",
    shopavatar: "assets/image/shop-image (6).jpg",
    title: "Bành mì chả nóng Dũng",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (7).jpg",
    shopavatar: "assets/image/shop-image (7).jpg",
    title: "Daebak - Thịt Nướng Hàn Quốc",
    title2: "còn 1",
    price: "25.000",
    type: "gói đồ ăn surprice",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (8).jpg",
    shopavatar: "assets/image/shop-image (8).jpg",
    title: "Kem Trái Dừa & Thạch Dừa",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "11:00",
    shopcover: "assets/image/shop-image (9).jpg",
    shopavatar: "assets/image/shop-image (9).jpg",
    title: "Bành mì chả nóng Dũng",
    title2: "còn 2",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (10).jpg",
    shopavatar: "assets/image/shop-image (10).jpg",
    title: "Cheap Corner -  Ship Đồ Ăn Đêm",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (11).jpg",
    shopavatar: "assets/image/shop-image (11).jpg",
    title: "Hồng Kỳ Quán -Lẩu Các Loại",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (12).jpg",
    shopavatar: "assets/image/shop-image (12).jpg",
    title: "Hồng Kỳ Quán -Lẩu Các Loại",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (13).jpg",
    shopavatar: "assets/image/shop-image (13).jpg",
    title: "Bún Ngan Hòe Nhai",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (14).jpg",
    shopavatar: "assets/image/shop-image (14).jpg",
    title: "Bánh cuốn",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (15).jpg",
    shopavatar: "assets/image/shop-image (15).jpg",
    title: "Tiger Sugar Fruit & Tea",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (16).jpg",
    shopavatar: "assets/image/shop-image (16).jpg",
    title: "Tiệm Mỳ Indo Bảo Ngân",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (17).jpg",
    shopavatar: "assets/image/shop-image (17).jpg",
    title: "Teen's Food",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (18).jpeg",
    shopavatar: "assets/image/shop-image (18).jpeg",
    title: "Lẩu Gà Hầm Sâm Hàn Quốc",
    title2: "còn 1",
    price: "34.000",
    type: "đồ ăn nóng",
    distance: "1km",
    rate: "3.3",
  ),
  Product(
    date: "12:00-13:00",
    shopcover: "assets/image/shop-image (19).jpg",
    shopavatar: "assets/image/shop-image (19).jpg",
    title: "Bà Thìn - Xôi Chè & Bánh Trôi",
    title2: "còn 1",
    price: "15.000",
    type: "đồ ăn nguội",
    distance: "1km",
    rate: "4.3",
  ),
];
